language: 
- python
- bash
os:
- linux
- osx
- windows

services:
- docker
sudo: required

before_install:
- pip install -U docker-compose
scrip:
- pip install -U docker-compose
- cd hzero-server/ && docker-compose run -d && docker-compose down
