language: 
- python
- bash
os:
- linux
- osx
- windows

services:
- docker
sudo: required
script:
- cd hzero-server/ && docker-compose up -f docker-compose.yaml --force-recreate --exit-code-from hzero-ci
