language: 
- python
- bash
os:
- linux
- osx
- windows

services:
- docker
sudo: required
script:
- cd hzero-server/ && docker-compose -f docker-compose.yaml config
- docker-compose -f docker-compose.yaml up -d --force-recreate 
- docker-compose -f docker-compose.yaml down
