language: 
- python
- bash
os:
- linux
- osx
- windows

services:
- docker
sudo: required

before_install:
- pip install -r requirements.txt 
scrip:
- cd hzero-server/ && docker-compose run -d && docker-compose down
